"""query_logs

Revision ID: 500a35229882
Revises: 0006_tsv_unaccent
Create Date: 2026-07-22 21:50:19.458342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '500a35229882'
down_revision: Union[str, None] = '0006_tsv_unaccent'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('query_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pregunta', sa.Text(), nullable=False),
    sa.Column('answered', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('chunks', sa.JSON(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('query_logs')
    # ### end Alembic commands ###
